language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.0-preview

    # The SDK version used to compile your project
    - android-23

    # Additional components
    # - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-23
before_install:
    - sudo apt-get -qq update
    - sudo add-apt-repository ppa:webupd8team/java
    - sudo apt-get install -y oracle-java8-installer
install: bash crosswalk/xwalkinstaller.sh auto --nominify
script: gradle clean assembleDebug
